version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "/"
      - "/.github/actions/deps-cache"
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns: ["*"]
